// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * UpdateInfo 返回给前端的更新信息。
 */
export class UpdateInfo {
    "has_update": boolean;
    "force_update": boolean;
    "current": string;
    "latest": string;
    "body": string;
    "download_url": string;
    "file_size": number;

    /** Creates a new UpdateInfo instance. */
    constructor($$source: Partial<UpdateInfo> = {}) {
        if (!("has_update" in $$source)) {
            this["has_update"] = false;
        }
        if (!("force_update" in $$source)) {
            this["force_update"] = false;
        }
        if (!("current" in $$source)) {
            this["current"] = "";
        }
        if (!("latest" in $$source)) {
            this["latest"] = "";
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("download_url" in $$source)) {
            this["download_url"] = "";
        }
        if (!("file_size" in $$source)) {
            this["file_size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo($$parsedSource as Partial<UpdateInfo>);
    }
}
