// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../time/models.js";

export class Account {
    "id": string;
    "name": string;
    "email"?: string;
    "user_type"?: string;
    "plan"?: string;

    /**
     * "pat" | "oauth"
     */
    "auth_mode": string;

    /**
     * "openai" | "anthropic" | "gemini" | "claude-code"
     */
    "api_mode": string;
    "tags": string[];
    "created_at": time$0.Time;
    "last_used"?: time$0.Time | null;
    "active": boolean;
    "sort_order": number;

    /** Creates a new Account instance. */
    constructor($$source: Partial<Account> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("auth_mode" in $$source)) {
            this["auth_mode"] = "";
        }
        if (!("api_mode" in $$source)) {
            this["api_mode"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }
        if (!("active" in $$source)) {
            this["active"] = false;
        }
        if (!("sort_order" in $$source)) {
            this["sort_order"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Account instance from a string or object.
     */
    static createFrom($$source: any = {}): Account {
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField7_0($$parsedSource["tags"]);
        }
        return new Account($$parsedSource as Partial<Account>);
    }
}

export class OAuthSession {
    "login_id": string;
    "login_url": string;

    /** Creates a new OAuthSession instance. */
    constructor($$source: Partial<OAuthSession> = {}) {
        if (!("login_id" in $$source)) {
            this["login_id"] = "";
        }
        if (!("login_url" in $$source)) {
            this["login_url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OAuthSession instance from a string or object.
     */
    static createFrom($$source: any = {}): OAuthSession {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OAuthSession($$parsedSource as Partial<OAuthSession>);
    }
}

export class QuotaBucket {
    "used": number;
    "total": number;
    "remaining": number;
    "reset_time"?: string;

    /** Creates a new QuotaBucket instance. */
    constructor($$source: Partial<QuotaBucket> = {}) {
        if (!("used" in $$source)) {
            this["used"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("remaining" in $$source)) {
            this["remaining"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuotaBucket instance from a string or object.
     */
    static createFrom($$source: any = {}): QuotaBucket {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QuotaBucket($$parsedSource as Partial<QuotaBucket>);
    }
}

export class QuotaInfo {
    "plan": string;
    "user_quota"?: QuotaBucket | null;
    "addon_quota"?: QuotaBucket | null;
    "is_quota_exceeded": boolean;

    /** Creates a new QuotaInfo instance. */
    constructor($$source: Partial<QuotaInfo> = {}) {
        if (!("plan" in $$source)) {
            this["plan"] = "";
        }
        if (!("is_quota_exceeded" in $$source)) {
            this["is_quota_exceeded"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuotaInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): QuotaInfo {
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("user_quota" in $$parsedSource) {
            $$parsedSource["user_quota"] = $$createField1_0($$parsedSource["user_quota"]);
        }
        if ("addon_quota" in $$parsedSource) {
            $$parsedSource["addon_quota"] = $$createField2_0($$parsedSource["addon_quota"]);
        }
        return new QuotaInfo($$parsedSource as Partial<QuotaInfo>);
    }
}

export class Settings {
    "port": number;
    "auto_start": boolean;

    /**
     * "info" | "debug" | "error"
     */
    "log_level": string;

    /**
     * 秒，0=不自动刷新
     */
    "quota_refresh_interval": number;

    /**
     * 自定义鉴权 token，空则使用默认值 "qccg"
     */
    "bridge_token"?: string;

    /**
     * [DEPRECATED] 旧扁平映射（向后兼容，MapModel 中作为兜底回退使用）
     */
    "model_mapping"?: { [_ in string]?: string };

    /**
     * agent (claude/codex/gemini) → 客户端模型名 → Qoder model.key
     */
    "model_mappings"?: { [_ in string]?: { [_ in string]?: string } };

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("auto_start" in $$source)) {
            this["auto_start"] = false;
        }
        if (!("log_level" in $$source)) {
            this["log_level"] = "";
        }
        if (!("quota_refresh_interval" in $$source)) {
            this["quota_refresh_interval"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        const $$createField5_0 = $$createType3;
        const $$createField6_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("model_mapping" in $$parsedSource) {
            $$parsedSource["model_mapping"] = $$createField5_0($$parsedSource["model_mapping"]);
        }
        if ("model_mappings" in $$parsedSource) {
            $$parsedSource["model_mappings"] = $$createField6_0($$parsedSource["model_mappings"]);
        }
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

export class Status {
    "running": boolean;
    "port": number;
    "active_account": string;
    "api_mode": string;

    /** Creates a new Status instance. */
    constructor($$source: Partial<Status> = {}) {
        if (!("running" in $$source)) {
            this["running"] = false;
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("active_account" in $$source)) {
            this["active_account"] = "";
        }
        if (!("api_mode" in $$source)) {
            this["api_mode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     */
    static createFrom($$source: any = {}): Status {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Status($$parsedSource as Partial<Status>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = QuotaBucket.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = $Create.Map($Create.Any, $$createType3);
