// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App 持有 Wails v3 的 app 和 window 引用，替代 v2 的 ctx。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as account$0 from "./account/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as logger$0 from "./logger/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddAccountByPAT(pat: string): $CancellablePromise<account$0.Account | null> {
    return $Call.ByName("main.App.AddAccountByPAT", pat).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ApplyClientConfig(clientType: string, model: string): $CancellablePromise<void> {
    return $Call.ByName("main.App.ApplyClientConfig", clientType, model);
}

/**
 * BackupClientConfigFile 在保存前把原文件备份到 ~/.qccg/backups/<type>_config.bak
 */
export function BackupClientConfigFile(clientType: string): $CancellablePromise<void> {
    return $Call.ByName("main.App.BackupClientConfigFile", clientType);
}

export function CancelOAuthLogin(loginID: string): $CancellablePromise<void> {
    return $Call.ByName("main.App.CancelOAuthLogin", loginID);
}

/**
 * CleanupAllData 清理 qccg 产生的本地数据与注入配置。
 */
export function CleanupAllData(): $CancellablePromise<void> {
    return $Call.ByName("main.App.CleanupAllData");
}

export function ClearLogs(): $CancellablePromise<void> {
    return $Call.ByName("main.App.ClearLogs");
}

export function Confirm(title: string, message: string): $CancellablePromise<boolean> {
    return $Call.ByName("main.App.Confirm", title, message);
}

export function DeleteAccount(id: string): $CancellablePromise<void> {
    return $Call.ByName("main.App.DeleteAccount", id);
}

export function GetAccountQuota(accountID: string): $CancellablePromise<account$0.QuotaInfo | null> {
    return $Call.ByName("main.App.GetAccountQuota", accountID).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetClientConfigs(): $CancellablePromise<$models.ClientConfig[]> {
    return $Call.ByName("main.App.GetClientConfigs").then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetLogs(limit: number): $CancellablePromise<logger$0.Entry[]> {
    return $Call.ByName("main.App.GetLogs", limit).then(($result: any) => {
        return $$createType7($result);
    });
}

export function GetLogsSince(afterSeq: number, limit: number): $CancellablePromise<logger$0.LogPage> {
    return $Call.ByName("main.App.GetLogsSince", afterSeq, limit).then(($result: any) => {
        return $$createType8($result);
    });
}

export function GetSettings(): $CancellablePromise<account$0.Settings | null> {
    return $Call.ByName("main.App.GetSettings").then(($result: any) => {
        return $$createType10($result);
    });
}

export function GetStatus(): $CancellablePromise<account$0.Status> {
    return $Call.ByName("main.App.GetStatus").then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * HasClientConfigBackup 返回指定 client 是否存在备份文件
 */
export function HasClientConfigBackup(clientType: string): $CancellablePromise<boolean> {
    return $Call.ByName("main.App.HasClientConfigBackup", clientType);
}

export function HideWindow(): $CancellablePromise<void> {
    return $Call.ByName("main.App.HideWindow");
}

export function ListAccounts(): $CancellablePromise<account$0.Account[]> {
    return $Call.ByName("main.App.ListAccounts").then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * ListQoderModels 通过当前激活账号的 bridge 拉取 Qoder 上游可用模型列表。
 */
export function ListQoderModels(): $CancellablePromise<$models.QoderModel[]> {
    return $Call.ByName("main.App.ListQoderModels").then(($result: any) => {
        return $$createType14($result);
    });
}

export function QuitApp(): $CancellablePromise<void> {
    return $Call.ByName("main.App.QuitApp");
}

export function ReadClientConfigFile(clientType: string): $CancellablePromise<$models.ClientConfigFile | null> {
    return $Call.ByName("main.App.ReadClientConfigFile", clientType).then(($result: any) => {
        return $$createType16($result);
    });
}

export function RemoveClientConfig(clientType: string): $CancellablePromise<void> {
    return $Call.ByName("main.App.RemoveClientConfig", clientType);
}

export function ReorderAccounts(ids: string[]): $CancellablePromise<void> {
    return $Call.ByName("main.App.ReorderAccounts", ids);
}

/**
 * RestoreClientConfigFile 把备份文件还原回原路径，还原后删除备份
 */
export function RestoreClientConfigFile(clientType: string): $CancellablePromise<void> {
    return $Call.ByName("main.App.RestoreClientConfigFile", clientType);
}

export function SaveAdditionalClientConfigFile(clientType: string, path: string, format: string, content: string): $CancellablePromise<void> {
    return $Call.ByName("main.App.SaveAdditionalClientConfigFile", clientType, path, format, content);
}

export function SaveClientConfigFile(clientType: string, content: string): $CancellablePromise<void> {
    return $Call.ByName("main.App.SaveClientConfigFile", clientType, content);
}

export function SaveSettings(s: account$0.Settings | null): $CancellablePromise<void> {
    return $Call.ByName("main.App.SaveSettings", s);
}

export function SetActiveAccount(id: string): $CancellablePromise<void> {
    return $Call.ByName("main.App.SetActiveAccount", id);
}

export function StartBridge(): $CancellablePromise<void> {
    return $Call.ByName("main.App.StartBridge");
}

export function StartOAuthLogin(): $CancellablePromise<account$0.OAuthSession | null> {
    return $Call.ByName("main.App.StartOAuthLogin").then(($result: any) => {
        return $$createType18($result);
    });
}

export function StopBridge(): $CancellablePromise<void> {
    return $Call.ByName("main.App.StopBridge");
}

/**
 * UpdateAccountAPIMode 更新账号的 API 模式
 */
export function UpdateAccountAPIMode(accountID: string, apiMode: string): $CancellablePromise<void> {
    return $Call.ByName("main.App.UpdateAccountAPIMode", accountID, apiMode);
}

export function WaitOAuthLogin(loginID: string): $CancellablePromise<void> {
    return $Call.ByName("main.App.WaitOAuthLogin", loginID);
}

export function GetVersion(): $CancellablePromise<string> {
    return $Call.ByName("main.App.GetVersion");
}

export function CheckUpdate(): $CancellablePromise<$models.UpdateInfo | null> {
    return $Call.ByName("main.App.CheckUpdate").then(($result: any) => {
        return $$createTypeUpdateInfo($result);
    });
}

export function ApplyUpdate(): $CancellablePromise<void> {
    return $Call.ByName("main.App.ApplyUpdate");
}

// Private type creation functions
const $$createType0 = account$0.Account.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = account$0.QuotaInfo.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.ClientConfig.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = logger$0.Entry.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = logger$0.LogPage.createFrom;
const $$createType9 = account$0.Settings.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = account$0.Status.createFrom;
const $$createType12 = $Create.Array($$createType0);
const $$createType13 = $models.QoderModel.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = $models.ClientConfigFile.createFrom;
const $$createType16 = $Create.Nullable($$createType15);
const $$createType17 = account$0.OAuthSession.createFrom;
const $$createType18 = $Create.Nullable($$createType17);
const $$createTypeUpdateInfo = $Create.Nullable($models.UpdateInfo.createFrom);
