// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ClientConfig 是返回前端的客户端配置状态。
 *   - ConfigPath/BaseURL/EnvVars 仅作展示
 *   - Applied 表示「已经被 qccg 标注过」(由 Marker 字段判断，避免误判用户原本就有的配置)
 *   - Model 是当前配置文件里读出来的「主力」模型名（仅展示）
 */
export class ClientConfig {
    "type": string;
    "name": string;
    "icon": string;
    "config_path": string;
    "base_url": string;
    "env_vars": string;
    "model": string;
    "applied": boolean;
    "error"?: string;

    /** Creates a new ClientConfig instance. */
    constructor($$source: Partial<ClientConfig> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("icon" in $$source)) {
            this["icon"] = "";
        }
        if (!("config_path" in $$source)) {
            this["config_path"] = "";
        }
        if (!("base_url" in $$source)) {
            this["base_url"] = "";
        }
        if (!("env_vars" in $$source)) {
            this["env_vars"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("applied" in $$source)) {
            this["applied"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClientConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ClientConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClientConfig($$parsedSource as Partial<ClientConfig>);
    }
}

/**
 * ClientConfigFile 是返回前端的「主配置文件原文 + 路径」结构，用于编辑器展示
 */
export class ClientConfigFile {
    "path": string;
    "content": string;

    /**
     * "json" / "toml" / "dotenv"
     */
    "format": string;
    "existed": boolean;
    "extra_files"?: ClientConfigFile[];

    /** Creates a new ClientConfigFile instance. */
    constructor($$source: Partial<ClientConfigFile> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("format" in $$source)) {
            this["format"] = "";
        }
        if (!("existed" in $$source)) {
            this["existed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClientConfigFile instance from a string or object.
     */
    static createFrom($$source: any = {}): ClientConfigFile {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("extra_files" in $$parsedSource) {
            $$parsedSource["extra_files"] = $$createField4_0($$parsedSource["extra_files"]);
        }
        return new ClientConfigFile($$parsedSource as Partial<ClientConfigFile>);
    }
}

/**
 * QoderModel 定义在 main 包以确保 Wails 生成 main.QoderModel 绑定。
 */
export class QoderModel {
    "key": string;
    "display_name": string;
    "enable": boolean;
    "is_default": boolean;
    "max_input_tokens"?: number;

    /** Creates a new QoderModel instance. */
    constructor($$source: Partial<QoderModel> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("display_name" in $$source)) {
            this["display_name"] = "";
        }
        if (!("enable" in $$source)) {
            this["enable"] = false;
        }
        if (!("is_default" in $$source)) {
            this["is_default"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QoderModel instance from a string or object.
     */
    static createFrom($$source: any = {}): QoderModel {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QoderModel($$parsedSource as Partial<QoderModel>);
    }
}

/**
 * UpdateInfo 返回给前端的更新信息。
 */
export class UpdateInfo {
    "has_update": boolean;
    "current": string;
    "latest": string;
    "body": string;
    "download_url": string;
    "file_size": number;

    constructor($$source: Partial<UpdateInfo> = {}) {
        if (!("has_update" in $$source)) { this["has_update"] = false; }
        if (!("current" in $$source)) { this["current"] = ""; }
        if (!("latest" in $$source)) { this["latest"] = ""; }
        if (!("body" in $$source)) { this["body"] = ""; }
        if (!("download_url" in $$source)) { this["download_url"] = ""; }
        if (!("file_size" in $$source)) { this["file_size"] = 0; }
        Object.assign(this, $$source);
    }

    static createFrom($$source: any = {}): UpdateInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo($$parsedSource as Partial<UpdateInfo>);
    }
}

// Private type creation functions
const $$createType0 = ClientConfigFile.createFrom;
const $$createType1 = $Create.Array($$createType0);
