// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../time/models.js";

export class Entry {
    "seq": number;
    "time": time$0.Time;
    "level": Level;
    "message": string;

    /** Creates a new Entry instance. */
    constructor($$source: Partial<Entry> = {}) {
        if (!("seq" in $$source)) {
            this["seq"] = 0;
        }
        if (!("time" in $$source)) {
            this["time"] = null;
        }
        if (!("level" in $$source)) {
            this["level"] = Level.$zero;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Entry instance from a string or object.
     */
    static createFrom($$source: any = {}): Entry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Entry($$parsedSource as Partial<Entry>);
    }
}

export enum Level {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    LevelDebug = "debug",
    LevelInfo = "info",
    LevelError = "error",
};

export class LogPage {
    "entries": Entry[];
    "last_seq": number;

    /** Creates a new LogPage instance. */
    constructor($$source: Partial<LogPage> = {}) {
        if (!("entries" in $$source)) {
            this["entries"] = [];
        }
        if (!("last_seq" in $$source)) {
            this["last_seq"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogPage instance from a string or object.
     */
    static createFrom($$source: any = {}): LogPage {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField0_0($$parsedSource["entries"]);
        }
        return new LogPage($$parsedSource as Partial<LogPage>);
    }
}

// Private type creation functions
const $$createType0 = Entry.createFrom;
const $$createType1 = $Create.Array($$createType0);
