// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAccountByPAT(arg1) {
  return window['go']['main']['App']['AddAccountByPAT'](arg1);
}

export function CancelOAuthLogin(arg1) {
  return window['go']['main']['App']['CancelOAuthLogin'](arg1);
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function Confirm(arg1, arg2) {
  return window['go']['main']['App']['Confirm'](arg1, arg2);
}

export function DeleteAccount(arg1) {
  return window['go']['main']['App']['DeleteAccount'](arg1);
}

export function GetAccountQuota(arg1) {
  return window['go']['main']['App']['GetAccountQuota'](arg1);
}

export function GetLogs(arg1) {
  return window['go']['main']['App']['GetLogs'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function ListAccounts() {
  return window['go']['main']['App']['ListAccounts']();
}

export function ListQoderModels() {
  return window['go']['main']['App']['ListQoderModels']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function ReorderAccounts(arg1) {
  return window['go']['main']['App']['ReorderAccounts'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetActiveAccount(arg1) {
  return window['go']['main']['App']['SetActiveAccount'](arg1);
}

export function StartBridge() {
  return window['go']['main']['App']['StartBridge']();
}

export function StartOAuthLogin() {
  return window['go']['main']['App']['StartOAuthLogin']();
}

export function StopBridge() {
  return window['go']['main']['App']['StopBridge']();
}

export function UpdateAccountAPIMode(arg1, arg2) {
  return window['go']['main']['App']['UpdateAccountAPIMode'](arg1, arg2);
}

export function WaitOAuthLogin(arg1) {
  return window['go']['main']['App']['WaitOAuthLogin'](arg1);
}
