// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAccountByPAT(arg1) {
  return window['go']['main']['App']['AddAccountByPAT'](arg1);
}

export function ApplyClientConfig(arg1, arg2) {
  return window['go']['main']['App']['ApplyClientConfig'](arg1, arg2);
}

export function BackupClientConfigFile(arg1) {
  return window['go']['main']['App']['BackupClientConfigFile'](arg1);
}

export function CancelOAuthLogin(arg1) {
  return window['go']['main']['App']['CancelOAuthLogin'](arg1);
}

export function CleanupAllData() {
  return window['go']['main']['App']['CleanupAllData']();
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function Confirm(arg1, arg2) {
  return window['go']['main']['App']['Confirm'](arg1, arg2);
}

export function DeleteAccount(arg1) {
  return window['go']['main']['App']['DeleteAccount'](arg1);
}

export function GetAccountQuota(arg1) {
  return window['go']['main']['App']['GetAccountQuota'](arg1);
}

export function GetClientConfigs() {
  return window['go']['main']['App']['GetClientConfigs']();
}

export function GetLogs(arg1) {
  return window['go']['main']['App']['GetLogs'](arg1);
}

export function GetLogsSince(arg1, arg2) {
  return window['go']['main']['App']['GetLogsSince'](arg1, arg2);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function HasClientConfigBackup(arg1) {
  return window['go']['main']['App']['HasClientConfigBackup'](arg1);
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function ListAccounts() {
  return window['go']['main']['App']['ListAccounts']();
}

export function ListQoderModels() {
  return window['go']['main']['App']['ListQoderModels']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function ReadClientConfigFile(arg1) {
  return window['go']['main']['App']['ReadClientConfigFile'](arg1);
}

export function RemoveClientConfig(arg1) {
  return window['go']['main']['App']['RemoveClientConfig'](arg1);
}

export function ReorderAccounts(arg1) {
  return window['go']['main']['App']['ReorderAccounts'](arg1);
}

export function RestoreClientConfigFile(arg1) {
  return window['go']['main']['App']['RestoreClientConfigFile'](arg1);
}

export function SaveAdditionalClientConfigFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveAdditionalClientConfigFile'](arg1, arg2, arg3, arg4);
}

export function SaveClientConfigFile(arg1, arg2) {
  return window['go']['main']['App']['SaveClientConfigFile'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetActiveAccount(arg1) {
  return window['go']['main']['App']['SetActiveAccount'](arg1);
}

export function StartBridge() {
  return window['go']['main']['App']['StartBridge']();
}

export function StartOAuthLogin() {
  return window['go']['main']['App']['StartOAuthLogin']();
}

export function StopBridge() {
  return window['go']['main']['App']['StopBridge']();
}

export function UpdateAccountAPIMode(arg1, arg2) {
  return window['go']['main']['App']['UpdateAccountAPIMode'](arg1, arg2);
}

export function WaitOAuthLogin(arg1) {
  return window['go']['main']['App']['WaitOAuthLogin'](arg1);
}
