// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {account} from '../models';
import {main} from '../models';
import {logger} from '../models';

export function AddAccountByPAT(arg1:string):Promise<account.Account>;

export function ApplyClientConfig(arg1:string,arg2:string):Promise<void>;

export function CancelOAuthLogin(arg1:string):Promise<void>;

export function ClearLogs():Promise<void>;

export function Confirm(arg1:string,arg2:string):Promise<boolean>;

export function DeleteAccount(arg1:string):Promise<void>;

export function GetAccountQuota(arg1:string):Promise<account.QuotaInfo>;

export function GetClientConfigs():Promise<Array<main.ClientConfig>>;

export function GetLogs(arg1:number):Promise<Array<logger.Entry>>;

export function GetSettings():Promise<account.Settings>;

export function GetStatus():Promise<account.Status>;

export function HideWindow():Promise<void>;

export function ListAccounts():Promise<Array<account.Account>>;

export function ListQoderModels():Promise<Array<main.QoderModel>>;

export function QuitApp():Promise<void>;

export function ReadClientConfigFile(arg1:string):Promise<main.ClientConfigFile>;

export function RemoveClientConfig(arg1:string):Promise<void>;

export function ReorderAccounts(arg1:Array<string>):Promise<void>;

export function SaveClientConfigFile(arg1:string,arg2:string):Promise<void>;

export function SaveSettings(arg1:account.Settings):Promise<void>;

export function SetActiveAccount(arg1:string):Promise<void>;

export function StartBridge():Promise<void>;

export function StartOAuthLogin():Promise<account.OAuthSession>;

export function StopBridge():Promise<void>;

export function UpdateAccountAPIMode(arg1:string,arg2:string):Promise<void>;

export function WaitOAuthLogin(arg1:string):Promise<void>;
